version: "3"
services:
  tool_db:
    image: kartoza/postgis:13.0
    container_name: tool_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASS=${PG_PASSWORD}
      - POSTGRES_DBNAME=${PG_DATABASE}
    networks:
      - server_net

  tool_simulator:
    build:
      context: ../herramienta-resiliencia-simulador
      args:
        userpassword: ${MODEL_PASSWORD}
    image: tool_simulator
    container_name: tool_simulator
    restart: always
    networks:
      - server_net

  tool_server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: tool_server_dev
    container_name: tool_server_dev
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app #dev volume
    environment:
      - PG_HOST=tool_db
      - PG_PORT=5432
      - PG_DATABASE=${PG_DATABASE}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - GS_USER=${GS_USER}
      - GS_PASS=${GS_PASS}
      - MODEL_PASSWORD=${MODEL_PASSWORD}
    networks:
      - server_net

  geoserver:
    image: kartoza/geoserver:2.18.0
    container_name: geoserver
    ports:
      - "8080:8080"
    volumes:
      - ${GS_DATA_DIR}:/opt/geoserver/data_dir
    healthcheck:
      test: curl --fail -s http://localhost:8080/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
    environment:
      - GEOSERVER_ADMIN_USER=${GS_USER}
      - GEOSERVER_ADMIN_PASSWORD=${GS_PASS}
    networks:
      - server_net

networks:
  server_net:
    driver: bridge
